name: allenSDKenv
channels:
  - conda-forge
dependencies:
  - python==3.11.5
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - scipy
  - seaborn
  - datajoint
  - pypdf
  - pip
  
  - pip:
    - git+https://github.com/alleninstitute/allensdk

